// <auto-generated />
using System;
using DAB2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAB2.Migrations
{
    [DbContext(typeof(Helpsystem))]
    partial class HelpsystemModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("DAB2.Data.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentAuId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeacherAuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("courseId");

                    b.HasIndex("StudentAuId");

                    b.HasIndex("TeacherAuId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DAB2.Data.Exercise", b =>
                {
                    b.Property<int>("number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("helpwhere")
                        .HasColumnType("TEXT");

                    b.Property<string>("lecture")
                        .HasColumnType("TEXT");

                    b.HasKey("number");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("DAB2.Data.Student", b =>
                {
                    b.Property<int>("AuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("AuId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DAB2.Data.Teacher", b =>
                {
                    b.Property<int>("AuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("AuId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("DAB2.Data.Course", b =>
                {
                    b.HasOne("DAB2.Data.Student", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudentAuId");

                    b.HasOne("DAB2.Data.Teacher", null)
                        .WithMany("Courses")
                        .HasForeignKey("TeacherAuId");
                });
#pragma warning restore 612, 618
        }
    }
}
